### ISSUE TITLE
Wrap of NodeJS Functions

### ISSUE THREAD

**Issue by freeformflow** [pandastrike/fairmont#30]
I'm still not clear on the boundaries of Fairmont, so forgive me if this is outside the intended scope.  Would it be okay to provide a list of NodeJS functions that are wrapped in ES6 promises?  Where is the boundary between usefulness and [the bludgeon problem](https://www.pandastrike.com/posts/20141112-rspec-uncanny-valley)?

For example, in panda-cluster we make use of these two functions:

``` coffee
# Promise wrapper around Node's https module. Turns GET calls into promises.
https_get = (url) ->
  {https} = require "https"
  {promise} = require "when"

  promise (resolve, reject) ->
    https.get url
    .on "response", (response) ->
      resolve response
    .on "error", (error) ->
      reject error

# Promise wrapper around response events that read "data" from the response's body.
get_body = (response, encoding) ->
  {promise} = require "when"
  promise (resolve, reject) ->
    data = ""
    format = encoding || "utf8"

    response.setEncoding format
    .on "data", (chunk) ->
      data = data + chunk
    .on "end", ->
      resolve data
    .on "error", (error) ->
      reject error
```

**Comment by dyoder** [comment]
Tactical answer: [Shred](https://github.com/pandastrike/shred) already can help with this. You just describe the API and use normal JavaScript functions. Everything already returns promises, including a separate `data` promise.

Less tactically…

Why `fs` and not `http`? Why string functions but not date functions? I think I'm subconsciously applying a simple heuristic: _does a given category, such as string functions, warrant it's own library?_ 

We currently have only 9 string functions. That doesn't seem too bad. Even if we added a bunch more, they'd mostly be detached versions of methods on strings, ex: `trim`.

Shred only exports only one function: `resource`. But it's a fairly powerful function. So, clearly, the number of functions isn't the only metric I'm applying here. It's also complexity.

In any event, we (mostly Matthew and I) somehow came to the conclusion that HTTP required it's own libaries, one for the client (Shred) and one for the server (Patchboard, PBX). Thus, the helpers aren't in Fairmont.

Another factor: I generally like to avoid discontinuous jumps in interfaces.

If we provide a function like `http_get`, what happens if someone then decides they need to make `POST` request? Okay, we add `http_post`. At that point, we start thinking, okay, maybe we should support all the request methods and so we add more functions. If we keep going like this, we'll obviously end up with a general purpose HTTP library.

On the other hand, if we decide to draw the line somewhere, then we're forcing someone to rewrite all the code they wrote using our simple helper functions, or mix and match them, with a library like Shred. All because they had an incrementally more complex requirement.

With all the stuff we've supported so far, it's easy to imagine extending the library so that we can handle virtually the entire set of requirements for any given category, without violating the heuristic about it warranting a dedicated library.

For example, if someone needs a `trim` function, and they add it and send us a PR, it's pretty easy to imagine us accepting it. We're not slowing backing into what amounts to a framework for strings. It's just a bunch of trivial functions.

All that said, if we can clearly define the boundary where we say _this doesn't belong_, then it's fine. For example, we might decide that we're simply wrapping what's already in the Node HTTP and HTTPS client API so that it's a bit cleaner than what we get with when's `liftAll` and seamlessly handles the fact that we're dealing with a stream not a string.

On that last point, one thing I'm going to add shortly is a function that turns a stream into an iterator. Then we can add a `join` collector. That way, if you want the stream as a string, you can just do:

``` coffee
yield join add, stream response
```

which is so clean that I'm not even sure we need another helper to deal with it separately.

**Comment by dyoder** [comment]
I just realized that I've already written the `stream` method referenced in the previous comment. Only I named it `read_block`. I'm going to rename it to `stream`. The `join` function above might have a better name, too. It's basically `fold` except with no initial value. Or maybe `sum` should just work on iterator functions? Then we'd have:

``` coffee
yield sum stream response
```

**Comment by dyoder** [comment]
Okay, this ended up looking like this:

``` coffee
yield join stream response
```

To my mind, this is so concise that we could potentially remove (or at least rethink) the context object that is returned from Shred-generated methods. At the very least, we can simplify the code in Shred.
